spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/my_blog_db?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncodeding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Shanghai

mybatis:
  mapper-locations: classpath:com/zou/zyqblogs/mapper/impl/**.xml
  type-aliases-package: com.zou.zyqblogs.pojo
  configuration:
    map-underscore-to-camel-case: true


## pagehelper 分页插件
#分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。
#你也可以配置helperDialect属性来指定分页插件使用哪种方言。
pagehelper :
  helperDialect: mysql
#分页合理化参数，默认值为false。当该参数设置为 true 时，
#pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），
#会查询最后一页。默认false 时，直接根据参数进行查询。
  reasonable: true
#用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，
#不配置映射的用默认值， 默认值为
  params: count=countSql
#默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，
#查找到合适的值时就会自动分页。
  supportMethodsArguments: true

logging:
  level:
    com:
      zou:
        zyqblogs:
          mapper: debug

